@text = qw/hi am prathyusha/;
print "@text/n";
print "text[1]=$text[1]\n";
print "text[-1]=$text[-1]\n";
print "text[-2]=$text[-2]\n";
@days = (1..10);
print "@days\n";
@alpha =(a..z);
print "@alpha\n";
@table = qw\apple pineapple banana kiwi\;
print "table consists of \n  @table\n";
print scalar(@table)."\n";
push(@table,"cherries");
print "new table after pushing is \n @table\n";
print scalar(@table)."\n";
unshift(@table,"blueberries");
print"after using unshift \n @table \n";
print scalar(@table)."\n";
pop(@table);
print "\t after using pop element at max index is deleted \n\t @table \n";
print scalar(@table)."\n";
shift(@table);
print "\t after shift it deletes element at the begining at index 0 \n\t @table \n";
print scalar(@table)."\n";
@tab= @alpha[5..10];
print "extracted table from aplha is \t@tab \n";
splice ( @alpha,21,3,r..t);
print "after slicing alpha we get \t @alpha \n ";
